apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fraudshield

resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-ingress.yaml
  - consumer-deployment.yaml
  - producer-deployment.yaml
